### PR TITLE
Update Frechet Audio Distance to be compatible with Python 3. Various bug and typo fixes.

### PR DESCRIPTION
**Pull request by phi-line**
- Upgraded Python Beam to 2.14.0 (supports Python 3)

- Updated imports to reflect running fad from root folder

- Updated paths to reflect new tensorflow_models structure

- Added .gitignore

### CODE REVIEW

**Comment by phi-line** [comment]
@googlebot I signed it!

**Comment by phi-line** [comment]
@maniatis take a look at your leisure.

**Comment by maniatis** [comment]
Hi @phi-line,

As I mentioned, each subdirectory in the google-research/google-research belongs to a different research group. I'm only involved in the /cubert subdirectory currently, so I am not able to review your pull request.

Apologies.

Petros

**Comment by phi-line** [comment]
@sun51 @peterjliu any chance you could check this PR out?

**Comment by peterjliu** [comment]
Did you mean to add somebody else? I don't have anything to do with that project.

**Comment by phi-line** [comment]
> Did you mean to add somebody else? I don't have anything to do with that project.

Sorry, I saw you as a contributor here -- perhaps it was some formatting or re-organization that you did

**Pull request closed without merging**
