### PR TITLE
remove .data in NadamWCosineDecay

### PR DESCRIPTION
**Pull request by Mxbonn**
**Similar to https://github.com/pytorch/pytorch/pull/33640**
Removes all uses of .data from optimizers

**Reason:**
I was trying to use the PyTorch implementation of the Learned Optimizer List but each epoch my GPU memory would increase until I would get a cuda error because I ran out of memory.

This was due to the .data accesses that piled up my gpu memory.

### CODE REVIEW

**Comment by Mxbonn** [comment]
@lukemetz

**Comment by lukemetz** [comment]
Thank you so much! I am a bit of a pytorch noob so this is very much appreciated!
This looks good to me. LGTM

**Comment by lukemetz** [comment]
@Mxbonn : I am tracking down how to get this merged now. It might take a few days though, sorry!

**Comment by Mxbonn** [comment]
@lukemetz No problem! I'm already thankful that you provided a PyTorch version to begin with ;).

One more thing however, in my own version I also changed. 
```python
   defaults = dict(
        learning_rate=learning_rate,
        beta1=beta1,
```` 
and 
```python
        lr = get_cosine_learning_rate_fn(group["training_steps"],
                                         group["learning_rate"],
                                         group["min_learning_rate_mult"],
                                         group["constant_fraction"],
                                         group["warmup_fraction"])(
                                             state["step"])
```` 
to 
```python
   defaults = dict(
        lr=learning_rate,
        beta1=beta1,
```` 
and 
```python
        lr = get_cosine_learning_rate_fn(group["training_steps"],
                                         group["lr"],
                                         group["min_learning_rate_mult"],
                                         group["constant_fraction"],
                                         group["warmup_fraction"])(
                                             state["step"])
```` 
(i.e. `learning_rate` to `lr`)

Because in PyTorch learning rate schedulers will look for the `'lr'` group.
See https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py

Now I know that you're not supposed to use a learning rate scheduler with this optimizer (or am I wrong and are you still advised to use on?) but in my code base (and I assume in others as well) even a dummy learning rate scheduler will look for this parameter.

Do you want me to also create a pull-request or add an extra commit here for that?

**Comment by lukemetz** [comment]
Yeah, I would not recommend using any form of schedule when using this optimizer (we manage it internally). That being said, this is an easy fix for improved compatibility. I will make it.

**Comment by lukemetz** [comment]
Should be all set now. Thanks again! Do let me know if anything else comes up / how things go.

**Pull request merged**
